### PR TITLE
Requesting a review of the preliminary functional requirements 

### PR DESCRIPTION
**Pull request by frroossst**
- Selected parts and components for each sensor
- Specifying how many sensors of each type are needed
- Added a hardware interaction diagram
- Added datasheets for archival and future reference
- KiCAD model is incomplete and not to be reviewed for now

### CODE REVIEW

**Comment by ATGr8** [comment]
- Remove req.md and req_notes.md
- Hardware Interaction diagram should include Flow of information, communication Protocols and Power. 
- use the Shall and Should method to define the requirements
- "non functional requirements"  in a document called functional_reqs makes no sense, Im thinking these should be together with the non functional requirements and be a "should"
- Move materials to a different document, keep in mind the requirements are not solutions
- Why do we need a buzzer and a battery terminal?
- Anyway we will discuss the materials when we get further into the design, not looking into the materials any further.

**Comment by frroossst** [comment]
The buzzer is just for debugging and general IO purposes, like I can set it to beep when a function is called or something like that

The battery terminal is a hard cutoff of sorts, I wanted to have some sort of a switch but in a high vibrations environment switches seemed like a bad idea, so a terminal, where we take a wire and just screw it down, to connect the power, basically a manual arming switch. (inspired by some videos I watched on YouTube about model rocket flight boards)

**Comment by ATGr8** [comment]
Use LEDs for debugging, Buzzers take up space and make annoying noises lol

**Comment by frroossst** [comment]
But is it even a computer if it doesn't beep and boop?

**Comment by frroossst** [comment]
I have updated some things to reflect the review comments @ATGr8

**Comment by dhaussecker** [comment]
Do not say it, say "the flight computer"
You have confused should with shall, turn those around

It shall have capabilites of reading sensors of different types
- Remove shall be able to detect apogee as that is now enclosed in stages of flight, remvoe trigger chute deployment cause that is done by the recovery board
It shall be capable of transmitting and receiving over the CAN Bus
It shall log all of it's data internally 
It shall be capable of being programmed easily
It shall have features for visual debugging
It shall have capabilities to exapnd further in the future
It shall have sensor redundancy

All other parts are not required at this point as this is a requirements analysis. NO SOLUTIONS AT THIS POINT

**Comment by dhaussecker** [comment]
The flight computer shall have capabilites of reading sensors of different types
The flight computer shall be capable of transmitting and receiving over the CAN Bus
The flight computer log all of it's data internally 
The flight computer be capable of being programmed easily
The flight computer have features for visual debugging
The flight computer have capabilities to exapnd further in the future
The flight computer shall have sensor redundancy

**Comment by dhaussecker** [comment]
The flight computer shall have capabilites of reading sensors of different types
The flight computer shall be capable of transmitting and receiving over the CAN Bus
The flight computer shall log all of it's data  
The flight computer shall be capable of being programmed easily
The flight computer shall have features for being able to debug easily
The flight computer shall have capabilities to expand further in the future
The flight computer shall have sensor redundancy

**Pull request closed without merging**
